export const donotdisturbDes = 'Do not disturb is on. Rings and Notifications are off for all Ghost Chat. Turn Do not disturb off to change Rings/Notifications for individual lines.';
export const disturbDes = 'Do not disturb is off. Rings and Notifications are on for all Ghost Chat. Turn Do not disturb on to change Rings/Notifications for individual lines.';

export const issueTypes = [
  { value: 'General Question' },
  { value: 'Problem Making Calls' },
  { value: 'Listening to Recordings' },
  { value: 'Adding Minutes' },
  { value: 'Credit Card Declining' },
  { value: 'Billing Issue' },
  { value: 'Legal Request' },
];


export const credits = [
  {
    amount: 4.99,//per month
    name: 'Unlimited Ghost',
    call: 'Unlimited Calls',
    text: 'Unlimited Text Messages',
    picture: 'Unlimited Pictures',
    auto:'Renewable_text',
    price: 4.99,
    //google_id: 'android.test.purchased',
    google_id: 'unlimited_1',//unlimited_1Price
    apple_id:'com.symbaventures.ghostchat.25creditpack',
  },
  {
    amount: 3.99,
    name: 'Standard Ghost',
    call: '60 Minutes',
    text: '130 Text Messages',
    picture: 'Send Pictures',
    auto:'Non-renewable_text',
    price: 3.99,
    //google_id: 'android.test.purchased',
    google_id: 'standard',
    apple_id:'com.symbaventures.ghostchat.8creditpack',
  },
  {
    amount: 2.99,
    name: 'Text-Only Ghost',
    call: 'No Calling',
    text: '250 Text Messages',
    picture: 'No Pictures',
    auto:'Non-renewable_text',
    price: 2.99,
    //google_id: 'android.test.purchased',
    google_id: 'text_only',
    apple_id:'com.symbaventures.ghostchat.10creditpack',
  },
  {
    amount: 1.99 ,
    name: 'Basic Ghost',
    call: '20 Minutes',
    text: '60 Text Messages',
    picture: 'Send Pictures',
    auto:'Non-renewable_text',
    price: 1.99,
    //google_id: 'android.test.purchased',
    google_id: 'basic',
    apple_id:'com.symbaventures.ghostchat.15creditpack',
  },
];

export const GhostNumbers = [
  {
    id: 0,
    date: '2018-07-30 19:05:49',
    number: '5075553247',
    location: 'Albany, OR',
  },
  {
    id: 1,
    date: '2018-07-30 19:05:49',
    number: '5075553247',
    location: 'Albany, OR',
  },
  {
    id: 2,
    date: '2018-07-30 19:05:49',
    number: '5075553247',
    location: 'Albany, OR',
  },
  {
    id: 3,
    date: '2018-07-30 19:05:49',
    number: '5075553247',
    location: 'Albany, OR',
  },
  {
    id: 4,
    date: '2018-07-30 19:05:49',
    number: '5075553247',
    location: 'Albany, OR',
  },
  {
    id: 5,
    date: '2018-07-30 19:05:49',
    number: '5075553247',
    location: 'Albany, OR',
  },
  {
    id: 6,
    date: '2018-07-30 19:05:49',
    number: '5075553247',
    location: 'Albany, OR',
  },
];

export const loginDataMock = {
  status: 'success',
  user: [
    {
      id: 12,
      uuid: '',
      source: 'ios',
      created_at: '',
      banned: 0,
      cus_fingerprint: null,
      lastLoggedIp: '106.186.120.232',
      phoneNumber: null,
      confirmed: 'N',
      rate_counter: 0,
      playerId: null,
      accountKitUserID: null,
      accountKitToken: null,
      facebookUserID: null,
      isTrial: 1,
      trialDID: 20,
      trialStartDate: '',
      trialEndDate: '',
      did_id: null,
      freeCredits: 3,
      credits: 0,
      trialNumber: 4582073585,
      trialRegion: 'OR',
    },
  ],
  config: {
    app_name: 'GhostSMS',
    app_version: '1.0',
    admob_enabled: true,
    googleAnalytics_enabled: false,
    ratings_enabled: true,
    support_email: 'support@ghostsms.app',
    stripe_public_key: 'pk_live_xxxxx',
  },
  dids: [
    {
      did_id: 28,
      did: 3526230216,
      friendlyName: '(352)623-0216',
      rateCenter: 'ARCHER',
      region: 'FL',
      isoCounty: 'US',
      updated_at: '',
    },
  ],
};

export const demo_settings = {
  dnd: 0,
  notifications: 1,
  rings: 1,
  ghostcallerid: 1,
};

export const emojis = [
  {
    name: 'grinning',
  },
  {
    name: 'grin',
  },
  {
    name: 'joy',
  },
  {
    name: 'smiley',
  },
];

export const emojiData = [
  'grinning',
  'grin',
  'joy',
  'smiley',
  'smile',
  'sweat_smile',
  'laughing',
  'innocent',
  'smiling_imp',
  'wink',
  'blush',
  'yum',
  'relieved',
  'heart_eyes',
  'sunglasses',
  'smirk',
  'neutral_face',
  'expressionless',
  'unamused',
  'sweat',
  'pensive',
  'confused',
  'confounded',
  'kissing',
  'kissing_heart',
  'kissing_smiling_eyes',
  'kissing_closed_eyes',
  'stuck_out_tongue',
  'stuck_out_tongue_winking_eye',
  'stuck_out_tongue_closed_eyes',
  'disappointed',
  'worried',
  'angry',
  'rage',
  'cry',
  'persevere',
  'triumph',
  'disappointed_relieved',
  'frowning',
  'anguished',
  'fearful',
  'weary',
  'sleepy',
  'tired_face',
  'grimacing',
  'sob',
  'open_mouth',
  'hushed',
  'cold_sweat',
  'scream',
  'astonished',
  'flushed',
  'sleeping',
  'dizzy_face',
  'no_mouth',
  'mask',
  'zipper_mouth_face',
  'money_mouth_face',
  'face_with_thermometer',
  'nerd_face',
  'thinking_face',
  'face_with_head_bandage',
  'robot_face',
  'hugging_face',
  'the_horns',
  'hand',
];

export const NameToEmoji = {
  smile: 'ðŸ˜„',
  smiley: 'ðŸ˜ƒ',
  grinning: 'ðŸ˜€',
  wink: 'ðŸ˜‰',
  blush: 'ðŸ˜Š',
  unamused: 'ðŸ˜',
  stuck_out_tongue: 'ðŸ˜›',
  stuck_out_tongue_winking_eye: 'ðŸ˜œ',
  disappointed: 'ðŸ˜ž',
  cry: 'ðŸ˜¢',
  sob: 'ðŸ˜­',
};